export type RoomType = "cottage" | "building" | "house";

export interface Room {
  slug: string;
  name: string;
  type: RoomType;
  capacityMin: number;
  capacityMax: number;
  capacityLabel: string;
  priceWeekday: number;
  priceWeekend: number;
  priceWeekdayDisplay: string;
  priceWeekendDisplay: string;
  featured: boolean;
  noLinen: boolean;
  photo: string;
}

const BASE = "https://storage.yandexcloud.net/kaldy-media";

export const ROOMS: Room[] = [
  {
    slug: "cottage-1",
    name: "Коттедж №1",
    type: "cottage",
    capacityMin: 5,
    capacityMax: 6,
    capacityLabel: "5–6 мест",
    priceWeekday: 8500,
    priceWeekend: 10500,
    priceWeekdayDisplay: "8 500 ₽",
    priceWeekendDisplay: "10 500 ₽",
    featured: false,
    noLinen: false,
    photo: `${BASE}/cottage-1-photo-1.jpg`,
  },
  {
    slug: "cottage-7-8",
    name: "Коттедж №7 / №8",
    type: "cottage",
    capacityMin: 7,
    capacityMax: 7,
    capacityLabel: "7 мест",
    priceWeekday: 7200,
    priceWeekend: 9500,
    priceWeekdayDisplay: "7 200 ₽",
    priceWeekendDisplay: "9 500 ₽",
    featured: true,
    noLinen: false,
    photo: `${BASE}/cottage-7-8-photo-1.jpg`,
  },
  {
    slug: "cottage-10",
    name: "Коттедж №10",
    type: "cottage",
    capacityMin: 3,
    capacityMax: 4,
    capacityLabel: "3–4 места",
    priceWeekday: 5000,
    priceWeekend: 6000,
    priceWeekdayDisplay: "5 000 ₽",
    priceWeekendDisplay: "6 000 ₽",
    featured: false,
    noLinen: false,
    photo: `${BASE}/cottage-10-photo-1.jpg`,
  },
  {
    slug: "cottage-14",
    name: "Коттедж №14",
    type: "cottage",
    capacityMin: 8,
    capacityMax: 8,
    capacityLabel: "8 мест",
    priceWeekday: 6000,
    priceWeekend: 7000,
    priceWeekdayDisplay: "6 000 ₽",
    priceWeekendDisplay: "7 000–7 400 ₽",
    featured: false,
    noLinen: false,
    photo: `${BASE}/cottage-14-photo-1.jpg`,
  },
  {
    slug: "cottage-9",
    name: "Коттедж №9",
    type: "cottage",
    capacityMin: 4,
    capacityMax: 7,
    capacityLabel: "4–7 мест",
    priceWeekday: 4000,
    priceWeekend: 5500,
    priceWeekdayDisplay: "от 4 000 ₽",
    priceWeekendDisplay: "от 5 500 ₽",
    featured: false,
    noLinen: false,
    photo: `${BASE}/cottage-9-photo-1.jpg`,
  },
  {
    slug: "building-2",
    name: "Корпус №2",
    type: "building",
    capacityMin: 2,
    capacityMax: 6,
    capacityLabel: "2–6 мест",
    priceWeekday: 2500,
    priceWeekend: 3500,
    priceWeekdayDisplay: "от 2 500 ₽",
    priceWeekendDisplay: "от 3 500 ₽",
    featured: false,
    noLinen: false,
    photo: `${BASE}/building-2-photo-1.jpg`,
  },
  {
    slug: "town-15-17",
    name: "Коттеджи №15–17А",
    type: "cottage",
    capacityMin: 3,
    capacityMax: 3,
    capacityLabel: "3 места",
    priceWeekday: 2300,
    priceWeekend: 3700,
    priceWeekdayDisplay: "от 2 300 ₽",
    priceWeekendDisplay: "от 3 700 ₽",
    featured: false,
    noLinen: true,
    photo: `${BASE}/town-15-17-photo-1.jpg`,
  },
  {
    slug: "colored-houses",
    name: "Цветные домики",
    type: "house",
    capacityMin: 3,
    capacityMax: 5,
    capacityLabel: "3–5 мест",
    priceWeekday: 1900,
    priceWeekend: 3000,
    priceWeekdayDisplay: "от 1 900 ₽",
    priceWeekendDisplay: "от 3 000 ₽",
    featured: false,
    noLinen: true,
    photo: `${BASE}/colored-houses-photo-1.jpg`,
  },
  {
    slug: "fishing-houses",
    name: "Рыбацкие домики",
    type: "house",
    capacityMin: 2,
    capacityMax: 3,
    capacityLabel: "2–3 места",
    priceWeekday: 2000,
    priceWeekend: 2500,
    priceWeekdayDisplay: "от 2 000 ₽",
    priceWeekendDisplay: "от 2 500 ₽",
    featured: false,
    noLinen: true,
    photo: `${BASE}/fishing-houses-photo-1.jpg`,
  },
  {
    slug: "flower-house",
    name: "Цветочный домик",
    type: "house",
    capacityMin: 3,
    capacityMax: 3,
    capacityLabel: "3 места",
    priceWeekday: 2000,
    priceWeekend: 2500,
    priceWeekdayDisplay: "2 000 ₽",
    priceWeekendDisplay: "2 500 ₽",
    featured: false,
    noLinen: true,
    photo: `${BASE}/flower-house-photo-1.jpg`,
  },
];
